### ISSUE TITLE
Parent Child Component extension example

### ISSUE THREAD

**Issue by dimaosa** [dev4jam/ToDo#1]
Hi @dev4jam  , 

Thanks for the great example, could you explain please, why do we need 
```
protocol ParentDependencyChild : Dependency {}
``` 
and how to use it, because I could not find the use case for it. As I saw in your example and uber one, we always declare our Dependency's in a 
```
protocol ChildDependency: Dependency {}
``` 
and use them as provided in example 
```
extension ParentComponent: ChildDependency {
    // TODO: Implement properties to provide for Child scope.    
}
```

Thanks.

**Comment by dev4jam** [comment]
Hi @dimaosa, 

the whole point of this is to give a Child an opportunity to ask something (not common with other children) from it's Parent i.e. sub-dependency from services or maybe (from Uber TicTacToe tutorial) ask Parent to provide a view controller conforming to a specific Child's view protocol.

Clear or need some code?

PS: We have a slack community uber-ribs.slack.com. Would you like to join?

**Comment by dimaosa** [comment]
Yeah, clear enough @dev4jam , code example will also be good. Thank you, I would like to join uber-ribs.slack.com ( my email is dima.osadchy@gmail.com)

**Comment by dev4jam** [comment]
👍🏻 added!
