### ISSUE TITLE
realm is causing compiler error

### ISSUE THREAD

**Issue by ishanalone** [dev4jam/ToDo#3]
Realm is giving compiler error in Xcode 10. Do I have to do any settings.

**Comment by sergey-zhuravel** [comment]
I also had such a problem. I just commented out two lines, since Realm is not used in the project.

```
  #pod 'Realm'
  #pod 'RealmSwift'
```

**Comment by dev4jam** [comment]
Updated podfile. @zhuravel-sergey  Please update and check it again.
